- src/dapla_pseudo/__init__.py
- src/dapla_pseudo/constants.py
- src/dapla_pseudo/v1/__init__.py
- src/dapla_pseudo/v1/builder.py
- src/dapla_pseudo/v1/models.py
- src/dapla_pseudo/v1/ops.py
- tests/builder_examples.ipynb
- tests/pseudonymize_examples.ipynb
- tests/v1/test_builder.py
- tests/v1/test_depseudonymize.py
- tests/v1/test_models.py
- tests/v1/test_ops.py
- tests/v1/test_pseudonymize.py
- tests/v1/test_repseudonymize.py
This allows for simplified configuration of pseudonymization through a flow with named methods which may be suggested by an IDE.
* Support for common pseudonymization use cases with specific methods.
* Support for custom pseudo-rules.
* TODO: Support directly reading files.
See https://github.com/statisticsnorway/dapla-toolbelt-pseudo/blob/builder-ui/tests/builder_examples.ipynb for working examples.
Internal ref: https://statistics-norway.atlassian.net/browse/STAT-527
> Pseudonymization via builder pattern

- src/dapla_pseudo/v1/builder.py
- src/dapla_pseudo/v1/client.py
- src/dapla_pseudo/v1/ops.py
The timeout was hard-coded to 30 secs, which according to the [spec](https://requests.readthedocs.io/en/latest/user/advanced/?highlight=timeout#timeouts) will be applied to both the `connect` and the `read` timeouts. 
This PR will make this timeout configurable, so that end users can decide these values.
> Add configurable timeout

- tests/builder_examples.ipynb
Replace `.dataframe` with `.to_polars()` when accessing the `PseudonymizationResult` in the builder example notebook. This change ensures compatibility with the latest version of dapla_pseudo.
The current version of dapla_pseudo offers two ways to access the DataFrame of a `PseudonymizationResult` either `to_polars()` or `to_pandas()`.
> Update outdated builder example notebook

- CONTRIBUTING.md
- src/dapla_pseudo/v1/builder.py
- src/dapla_pseudo/v1/supported_file_format.py
- tests/v1/test_builder.py
- tests/v1/test_supported_file_format.py
The `PseudoData.from_file` function will now use polars when reading `parquet` formatted files. This should improve performance when reading `parquet`.
This resolves [issue#227](https://github.com/statisticsnorway/dapla-toolbelt-pseudo/issues/227)
I have opted not to use Polars for reading CSV files because it would necessitate us to handle a convertion between Polars 'dtypes' and Pandas 'dtype'.
Currently, all the file formats we support reading can either have data types specified with the `dtype` keyword argument or derive the schema from the file. We should avoid requiring users to define data types differently for CSV files. 
Pandas.[read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) dtypes:`dtype or dict of {Hashabledtype}` …
> Read files with polars

- src/dapla_pseudo/v1/ops.py
- tests/v1/test_pseudonymize.py
Using anything else than `str` as an argument in `fields` or `sid_fields` resulted in this error when creating a set:
`TypeError: unhashable type: 'dict'` or `TypeError: unhashable type: 'Field'`
Use tuples instead since they are immutable. Also check the field type before applying string type to the dataframe.
> Fix unhashable type exception

- pyproject.toml
This is in order to stop having to fiddle with pyproject.toml when importing Pandas
> Changed upper bound of Python version to match SciPy

- README.md
- pyproject.toml
- src/dapla_pseudo/v1/client.py
- tests/v1/test_pseudonymize.py
After the service was moved to k8s we use google credentials instead of a keycloak access token to authenticate with the Pseudo Service.
- Use google credentials instead of keycloak access token
- Update readme example('fetch_google_token'  relies on 'fetch_local_user', this means it only works from jupyter)
- Bump version
- Update tests
> Authenticate with Pseudo Service useing google credentials

- pyproject.toml
Now that SciPy supports 3.12, we can also do so
> Include Python 3.12

- .github/workflows/release.yml
[dapla-toolbelt-pseudo](https://github.com/statisticsnorway/dapla-toolbelt-pseudo) is now a trusted publisher for statisticsnorway on PyPi
> Fixed auth to pypi

- pyproject.toml
- src/dapla_pseudo/v1/result.py
- tests/v1/test_result.py
This is a workaround to the following issue: https://github.com/pola-rs/polars/issues/7291
The issue arises when, if you pre-process data in certain ways in Pandas, and write the file to Parquet, Pandas writes some metadata in a separate column called `__index_level_0__` Polars, however, does not handle these columns, and renders the data unreadable when using `pl.read_parquet()`
> Fix Polars bug

- src/dapla_pseudo/constants.py
- src/dapla_pseudo/v1/api_models.py
- tests/data/datadoc/expected_metadata_test_pseudonymize_sid.json
- tests/data/datadoc/expected_metadata_test_pseudonymize_sid_null.json
The default function for mapping SID is now `map-sid-ff31`. The former `map-sid` function is deprecated.
Internal ticket no: DPSTAT-901
> Change default map-sid function

- README.md
- pyproject.toml
- src/dapla_pseudo/__init__.py
- src/dapla_pseudo/v1/__init__.py
- src/dapla_pseudo/v1/api_models.py
- src/dapla_pseudo/v1/baseclass.py
- src/dapla_pseudo/v1/client.py
- src/dapla_pseudo/v1/depseudo.py
- src/dapla_pseudo/v1/pseudo.py
- src/dapla_pseudo/v1/pseudo_commons.py
- src/dapla_pseudo/v1/repseudo.py
- tests/conftest.py
- tests/data/personer_pseudonymized_default_encryption_ssb_common_key_2.csv
- tests/integration/test_integration_repseudonymize.py
- tests/v1/test_client.py
- tests/v1/test_depseudo.py
- tests/v1/test_pseudo.py
- tests/v1/test_repseudo.py
This PR implements repseudo in the builder pattern. We also made a common class for building `PseudoRules`. This should probably be re-used in `pseudo` and `depseudo`.
> Repseudo in builder pattern

- README.md
- src/dapla_pseudo/utils.py
- src/dapla_pseudo/v1/client.py
- src/dapla_pseudo/v1/validation.py
The Validator accepts both "str" and "date" as input types, so we don't need an explicit conversion to "date".
> Fix Validator documentation. Convert to date in Validator

- src/dapla_pseudo/__init__.py
- src/dapla_pseudo/v1/api_models.py
- tests/v1/test_api_models.py
One can now create a `PseudoRule` from json, and where the `PseudoFunction` is expressed by the shorthand serialized string format,  e.g. like this:
```
from dapla_pseudo import PseudoRule
rule = {
'name': 'my-fule',
'pattern': '**/identifiers/*',
'func': 'redact(placeholder=#)'
}
PseudoRule.from_json(rule)
```
> Add ability to deserialize PseudoFunction from json

- src/dapla_pseudo/utils.py
- src/dapla_pseudo/v1/baseclasses.py
- tests/v1/unit/test_base_pseudonymizer.py
The methods `build_pseudo_dataset_request` and `_pseudonymize_dataset` is renamed to `build_pseudo_file_request` and `_pseudonymize_file` since the operation interacts with the file endpoint.
> Refactor internal methods.

- tests/v1/integration/conftest.py
This is necessary to run the integration tests locally. gcloud, in the newest version, wants to write all logs to a /root folder when fetching an id-token. For some reason, changing the verbosity in the `gcloud` command does not silence this warning in the token output. So, we need to disable local logging to get the result cleanly.
> Disable gcloud local cloud logging

- pyproject.toml
- src/dapla_pseudo/v1/baseclasses.py
- tests/conftest.py
- tests/data/datadoc/expected_metadata_test_pseudonymize_hierarchical_redact.json
- tests/data/personer_hierarchical_redacted.json
- tests/v1/integration/test_pseudonymize.py
This PR makes it so that the library does redact-operations within the library - and does not make calls to Pseudo Service. A cursory test indicated something like 1000x improvement in performance (not very surprising).
Downside -> we need to duplicate metadata changes in both the library and the service. However, given the constraints on the automation tools we offer I think this is a worthwhile.
Also, SonarCloud is dumb and doesn't recognize our interation tests for coverage purposes :))
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-toolbelt-pseudo/410)
> Redact locally

- .cruft.json
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/workflows/constraints.txt
- .github/workflows/docs.yml
- .github/workflows/labeler.yml
- .github/workflows/pseudo-service-integration-test.yaml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
- src/dapla_pseudo/utils.py
- src/dapla_pseudo/v1/baseclasses.py
- src/dapla_pseudo/v1/client.py
- tests/data/datadoc/expected_metadata_test_pseudonymize_default_encryption_synchronous.json
- tests/v1/integration/test_pseudonymize.py
When running `dapla-toolbelt-pseudo` in an environment where programs are already being executed through an event loop (e.g Jupyter Notebook), this library, which also uses an event loop, cannot serve any requests. This is apparently a known issue with `asyncio`. This PR essentially restores the functionality removed in #412, but refactoring it into its own function. This library now detects whether the environment contains a running event loop, and uses synchronous requests if that is the case.
Also, rather embarassingly, #412 did remove the functionality introduced in #410, so this functionality has been re-introduced.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/d …
> Use synchronous requests when running in an env with an event loop

- pyproject.toml
- src/dapla_pseudo/v1/depseudo.py
- src/dapla_pseudo/v1/pseudo.py
- src/dapla_pseudo/v1/repseudo.py
- src/dapla_pseudo/v1/result.py
- tests/v1/integration/test_result.py
- tests/v1/unit/test_result.py
In the rare case where you'd want to both pseudonymize _and_ depseudonymize the same dataset, you'd typically chain the process like so:
```python
df = pl.read_parquet("gs://some_bucket/some_folder")
df = (
Pseudonymize
.from_polars(df)
.on_fields("fornavn","etternavn")
.with_default_encryption()
.run()
.to_polars()
)
result = (
Depseudonymize
.from_polars(df)
.on_fields("bolig")
.with_default_encryption()
.run()
)
```
However, collapsing the data structure from a `Result` to a `DataFrame` when calling `to_polars()` in the first result causes metadata in the `Result` object to be lost. This is not desirable, especially when pseudonymizing mostly finished data, because the metadata helps track the transition between different data brokers.
The feature in this PR allows you to use the …
> Construct a new builder from a previously generated result

- pyproject.toml
- src/dapla_pseudo/v1/client.py
By default, we only retry 5xx errors. The idea being that we only want to retry when the server is at fault. However, sometimes during scale down, some users experience the following error:
`aiohttp.http_exceptions.TransferEncodingError: 400, message: Not enough data for satisfy transfer length header`
The cost of retries isn't very large, so we now retry all 400 errors to account for this
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-toolbelt-pseudo/445)
> Retry all 400 errors
